### ISSUE TITLE
Download ERA5 reanalysis data error

### ISSUE THREAD

**Issue by georgeboldeanu** [DHI-GRAS/sen-et-snap-sta#3]
When i try to download ERA5 reanalysis data using SEN-ET plugins i get this **ERROR:Missing/incomplete configuration file: $USERPROFILE/.cdsapirc**. I configured correctly the .cdsapirc file and tested with the associated python(see the image).![era5](https://user-images.githubusercontent.com/34105846/71979974-ad403100-3227-11ea-90e3-7bc562dd10f9.JPG) 

All it works fine, i downloaded some test data. But when i use it in SNAP all the time i get the error.
![era523](https://user-images.githubusercontent.com/34105846/71980052-d95bb200-3227-11ea-9d45-c8c4f45a15b2.JPG)

 What can it cause it because i am out of ideas?

**Comment by j08lue** [comment]
The environment variable `$USERPROFILE` is not defined or for some reason not being expanded, so the `.cdsapirc` file cannot be found.

This could either be because the environment variable is not defined (check Windows environment variables) or because it is not visible from within the software for some reason. Please check whether it is defined, first, and set it to `C:\Users\<your-username>`, if not.

**Comment by georgeboldeanu** [comment]
The environment variable are defined both in windows environment and also in system variables  of the plugin (see the screen shots). None of the solutions is working a bit, at least if i get another error :(

![envi](https://user-images.githubusercontent.com/34105846/72043236-508d5680-32b9-11ea-8393-3cd478482c62.JPG)
![Capture](https://user-images.githubusercontent.com/34105846/72043318-8599a900-32b9-11ea-9c5a-5a206d9e56e2.JPG)

**Comment by j08lue** [comment]
Right, then it is an expansion issue. I remember we had them during development but fixed them. Maybe that was somewhere else. We'll investigate.

**Comment by georgeboldeanu** [comment]
Cheers @j08lue !

**Comment by panakouris** [comment]
We are aware of this bug in the Windows version. I hope that by the end of next week I will be able to push an update. @j08lue @georgeboldeanu

**Comment by panakouris** [comment]
@georgeboldeanu I have just fixed the reported bug and pushed the changes. In order to get the new version I would advice you to delete the folder `<USERPROFILE>\.snap\sen-et-conda-Win64` and try again to run one of the Sen-ET SNAP operators. After installing the provided bundle (updated) you will be able to run all the operators. For more information regarding the installation, please check also here `http://esa-sen4et.org/outputs/software/` (User manual).

**Comment by georgeboldeanu** [comment]
@panakouris I think this is a curse. I get the same error after reinstalling snap, python and all SEN-ET plugins also created another .cdsapirc file. I really don't find the problem of this. Any idea?

**Comment by panakouris** [comment]
@georgeboldeanu Did you make sure that you deleted the directory `<USERPROFILE>\.snap\sen-et-conda-Win64`? Did you see the pop-up attached in this message when you re-installed the plugin? And also, do you have the cds credentials stored in the following file `C:\Users\<YOUR_USER>\.cdsapirc`
![image](https://user-images.githubusercontent.com/24657463/72434280-817af900-379b-11ea-9e46-a7a1a3a014ae.png)

**Comment by georgeboldeanu** [comment]
@panakouris Yes, all checked. I deleted the whole .snap directory, reinstalled the snap software, install the plugins, configured the bundle and verified that the cds file with the credentials work with python(downloaded some data again). I configure SNAP on a new PC in my office and try there, i hope that will work. If so it's clearly that my computer is the problem and maybe i will format the OS. Let's wait and see. We'll keep in touch. Cheers!

**Comment by georgeboldeanu** [comment]
@panakouris  It's me again. It's still don't working neither on that computer. I'm kinda lost right now because the **`.cdsapirc`** file it's configured properly (tried the cds api via python on this computer also). All the thing is that i want to configure it for one of my collegue that's more used to use SNAP GUI. You can give me any other advices??

**Comment by panakouris** [comment]
@georgeboldeanu  I just borrowed a new computer to test it out. I will let you know soon.

**Comment by panakouris** [comment]
I can confirm there was still an issue with the `.cdsapirc` file location which I was able to reproduce and fix. I pushed a new updated version of the provided bundle. You can repeat the same procedure described in a previous message to re-install the bundle. In case there is still an issue, you can also set the environment variable `CDSAPI_RC` pointing to the `.cdsapirc` file in your computer.

**Comment by georgeboldeanu** [comment]
@panakouris This time it's done. Downloading ERA5 data it's running smooth as a '69 Camaro.

**Comment by c4rt0** [comment]
Hi guys - I can report same problem on mac. Everything works fine if code is ran directly from a directory where it was build, but the moment I'm using another script to activate it - I'm having same nightmare...
![Screenshot 2020-07-08 at 09 45 50](https://user-images.githubusercontent.com/22802831/86898063-1d107500-c100-11ea-8d87-db9fe7072a66.png)

**Comment by j08lue** [comment]
How about putting a copy (or symlink) of your config file in `/root/.cdsapirc`, where the script seems to be looking for it? Resolving user home is sometimes surprisingly hard for some code. If you can avoid it, I would not go down the rabbit hole of debugging that...

**Comment by shimamani** [comment]
Hi
I want to get the evapotranspiration according to sen-et but I get an error in the meteorological data download section.
When I download through the Snap program, I get the following error
 "raise Exception(error)
Exception: <html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.20.2</center>
</body>
</html>"
While I have registered on the site
url: https://cds.climate.copernicus.eu/api/v2
key: 17XXX:2425a141-05af-456c-9d0f-30d0563850b2

It shows the same error in Python, while I did all the steps according to the guide.

"raise InvalidSchema("No connection adapters were found for {!r}".format(url))
requests.exceptions.InvalidSchema: No connection adapters were found for 'C:/Users/SHIMA/resources/reanalysis-era5-single-levels'"

When I download the data from the site and continue the steps in Snap, I face the following error
"ERROR:Variable z does not exist in file C:\Users\SHIMA\Downloads\adaptor.mars.internal-1676666620.343337-32501-2-1a29493f-6402-46fe-b813-2fefe66e285f.nc."

Is there a way to add the z variable to the".nc" files? Or any way that this operation can be done automatically in Python,google Earth Engine, Snap programs?
